[package]
org = "PubuduGunatilaka"
name = "pet_management_service"
version = "1.0.0"
export = ["pet_management_service"]
include = ["resources"]
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true
